# Alternative Database Configuration Options
# Choose one of the following configurations:

# Option 1: H2 Database (for immediate testing)
spring:
  profiles:
    active: h2
  
---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:file:./data/contactdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    
    # HikariCP connection pool configuration optimized for HIGH TPS
    hikari:
      maximum-pool-size: 50
      minimum-idle: 15
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 300000
      max-lifetime: 900000
      auto-commit: false
      read-only: false
      connection-test-query: SELECT 1
      pool-name: ContactAPIHikariCP
      leak-detection-threshold: 30000
      initialization-fail-timeout: 1
      isolate-internal-queries: false
      allow-pool-suspension: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 500
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
      
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
          batch_versioned_data: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
        connection:
          provider_disables_autocommit: true
        temp:
          use_jdbc_metadata_defaults: false
        generate_statistics: false
    show-sql: false

---
# Option 2: MySQL Database (when password is configured)
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/contactdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: contactapi
    password: password
    
    # HikariCP connection pool configuration optimized for HIGH TPS
    hikari:
      maximum-pool-size: 50
      minimum-idle: 15
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 300000
      max-lifetime: 900000
      auto-commit: false
      read-only: false
      connection-test-query: SELECT 1
      pool-name: ContactAPIHikariCP
      leak-detection-threshold: 30000
      initialization-fail-timeout: 1
      isolate-internal-queries: false
      allow-pool-suspension: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 500
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
      
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
          batch_versioned_data: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
        connection:
          provider_disables_autocommit: true
        temp:
          use_jdbc_metadata_defaults: false
        generate_statistics: false
    show-sql: false

# Common configuration for both profiles
server:
  port: ${SERVER_PORT:8081}
  tomcat:
    threads:
      max: 500
      min-spare: 50
    connection-timeout: 10000
    accept-count: 200
    max-connections: 10000
    max-http-form-post-size: 2MB
    max-http-header-size: 8KB
    processor-cache: 500
    keep-alive-timeout: 20000
    max-keep-alive-requests: 1000

logging:
  level:
    com.keviny.customercontact: INFO
    com.zaxxer.hikari: INFO
    org.hibernate.SQL: WARN
    root: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,hikaricp
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      simple:
        enabled: true