micronaut:
  application:
    name: customer-contact
  server:
    port: ${SERVER_PORT:8081}
    netty:
      worker:
        threads: 16
      max-header-size: 8KB
  data:
    pageable:
      max-page-size: 100
  http:
    client:
      read-timeout: 30s
  transaction:
    read-only: false

datasources:
  default:
    url: jdbc:h2:file:./data/contactdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ""
    # HikariCP connection pool configuration optimized for HIGH TPS
    hikari:
      maximum-pool-size: 50
      minimum-idle: 15
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 300000
      max-lifetime: 900000
      auto-commit: false
      read-only: false
      connection-test-query: SELECT 1
      pool-name: ContactAPIHikariCP
      leak-detection-threshold: 30000
      initialization-fail-timeout: 1
      isolate-internal-queries: false
      allow-pool-suspension: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 500
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
          batch_versioned_data: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
        connection:
          provider_disables_autocommit: true
        temp:
          use_jdbc_metadata_defaults: false
        generate_statistics: false
        show_sql: false

jackson:
  deserialization:
    failOnUnknownProperties: true

logger:
  levels:
    com.keviny.customercontact: INFO
    com.zaxxer.hikari: INFO
    org.hibernate.SQL: WARN
    ROOT: WARN

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
  info:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: false

# Resilience4j configuration for fault tolerance
resilience4j:
  circuitbreaker:
    instances:
      contactService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
        
  retry:
    instances:
      contactService:
        maxAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.dao.DataAccessException
          - java.sql.SQLException
        ignoreExceptions:
          - java.lang.IllegalArgumentException
          - jakarta.validation.ConstraintViolationException
          
  ratelimiter:
    instances:
      contactService:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 500ms